INSERT INTO family (name)
VALUES
    ("Huile essentielle"),
    ("Exfoliant"),
    ("Actif cosmetique"),
    ("Poudre de plante"),
    ("Cire"),
    ("Emulsifiant"),
    ("Beurre"),
    ("Colorant"),
    ("Conservateur"),
    ("Base"),
    ("Fragrance"),
    ("Huile vegetale");

INSERT INTO usage (name)
VALUES
    ("diffusion"),
    ("creme"),
    ("application cutanée"),
    ("masque cheveux"),
    ("savon"),
    ("maquillage");

INSERT INTO property (name)
VALUES
    ("Confort respiratoire"),
    ("Assainissement de l'air"),
    ("Purifiante"),
    ("Rafraîchissante"),
    ("Apaisante"),
    ("Anti-inflammatoire"),
    ("Cheveux blonds"),
    ("Peaux reactives"),
    ("Antibacterienne"),
    ("Tonifiante pour le cuir chevelu"),
    ("Maux de tête"),
    ("Demangeaison"),
    ("Tonique"),
    ("Assainissante"),
    ("Peau acneique"),
    ("Revigorante"),
    ("Antiseptique"),
    ("régulation sudorifique"),
    ("jambes lourdes"),
    ("Cuisine"),
    ("Matifiant"),
    ("Epaissisant"),
    ("Stabilisant"),
    ("Bougie"),
    ("Auto-émulsifiant"),
    ("Conditionneur capillaire"),
    ("Decontractant musculaire"),
    ("Detoxifiant"),
    ("Hydratant"),
    ("Colorant"),
    ("Antioxydant"),
    ("Anti-age"),
    ("Nettoyante"),
    ("Raffermissant"),
    ("Senteur"),
    ("Conservateur"),
    ("Reparateur"),
    ("Deodorant"),
    ("Fortifiant cheveux");